steps:
  # STEP 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/gen-lang-client-0307115404/rtiqa/rtiqa-ktor-api:$COMMIT_SHA'
      - '-f'
      - 'deploy/ktor-starter/Dockerfile'
      - '.'

  # STEP 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/gen-lang-client-0307115404/rtiqa/rtiqa-ktor-api:$COMMIT_SHA'

  # STEP 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'rtiqa-ktor-api'
      - '--image=asia-south1-docker.pkg.dev/gen-lang-client-0307115404/rtiqa/rtiqa-ktor-api:$COMMIT_SHA'
      - '--region=asia-south1'
      - '--service-account=rtiqa-cloud-run-runtime@gen-lang-client-0307115404.iam.gserviceaccount.com'
      - '--set-secrets=SUPABASE_URL=SUPABASE_URL:1,SUPABASE_PUBLISHABLE_KEY=SUPABASE_PUBLISHABLE_KEY:1,DATABASE_URL=DATABASE_URL:1,DATABASE_USER=DATABASE_USER:1,DATABASE_PASSWORD=DATABASE_PASSWORD:2'

options:
  logging: CLOUD_LOGGING_ONLY
